'use client';

import { Children, cloneElement, isValidElement, useEffect, useMemo, useState } from 'react';
import { COST_CATEGORIES, COST_BASES, CONFIRMATIONS, type CostCategory, type CostLine, type CostingInput, type JourneyContext, type JourneyCosting } from '@/models/JourneyCosting';
import { calculateJourneyCosting, emptyCosting, emptyLine } from '@/services/pricing/journeyCosting.service';
import Link from 'next/link';
import SupplierRatePicker from '@/components/internal/SupplierRatePicker';
import SupplierQuoteHelper from '@/components/internal/SupplierQuoteHelper';

const labels: Record<CostCategory, string> = { hotelCosts: 'Hotels', transportCosts: 'Transport', mealCosts: 'Meals', activityCosts: 'Activities', permitCosts: 'Permits', localServiceCosts: 'Local services', miscCosts: 'Miscellaneous' };
const inputClass = 'mt-1 w-full min-w-0 rounded-lg border border-slate-300 bg-white p-2 text-sm text-slate-900';
const buttonClass = 'rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-800 hover:bg-slate-100 disabled:opacity-40';
const currency = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(n);
function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="block min-w-0 text-xs font-medium text-slate-600">{label}{Children.map(children, child =>
    isValidElement(child) && ['input', 'select', 'textarea'].includes(String(child.type))
      ? cloneElement(child as React.ReactElement<{ 'aria-label'?: string }>, { 'aria-label': label }) : child)}</label>;
}
function Numeric({ label, value, onChange, nullable = false }: { label: string; value: number | null; onChange: (n: number | null) => void; nullable?: boolean }) {
  return <Field label={label}><input className={inputClass} type="number" min="0" step="any" value={value ?? ''} onChange={event => onChange(event.target.value === '' ? (nullable ? null : 0) : Number(event.target.value))} /></Field>;
}
export default function JourneyCostingClient() {
  const [journeys, setJourneys] = useState<JourneyContext[]>([]); const [revisions, setRevisions] = useState<JourneyCosting[]>([]);
  const [input, setInput] = useState<CostingInput | null>(null); const [saved, setSaved] = useState<JourneyCosting | null>(null);
  const [message, setMessage] = useState('Loading Journey context…'); const [busy, setBusy] = useState(false); const [reviewer, setReviewer] = useState(''); const [confirmed, setConfirmed] = useState(false); const [applyText, setApplyText] = useState('');
  useEffect(() => { let active = true; fetch('/api/internal/journey-costing', { cache: 'no-store' }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); if (!active) return; setJourneys(data.journeys); setRevisions(data.revisions); const first = data.journeys.find((row: JourneyContext) => row.status === 'draft') ?? data.journeys[0]; if (first) setInput(emptyCosting(first)); setMessage('Supplier costs are blank. Enter a real quote to begin.'); }).catch(error => { if (active) setMessage(error.message); }); return () => { active = false; }; }, []);
  const journey = journeys.find(row => row.journeyId === input?.journeyId);
  const result = useMemo(() => { try { return input ? { calculation: calculateJourneyCosting(input), error: '' } : null; } catch (error) { return { calculation: null, error: error instanceof Error ? error.message : 'Invalid costing' }; } }, [input]);
  const dirty = !!saved && JSON.stringify(saved.input) !== JSON.stringify(input);
  function update(patch: Partial<CostingInput>) { setConfirmed(false); setApplyText(''); setInput(current => current ? { ...current, ...patch } : current); }
  function updateLine(category: CostCategory, id: string, patch: Partial<CostLine>) { if (input) update({ [category]: input[category].map(line => line.id === id ? { ...line, ...patch } : line) }); }
  async function action(payload: unknown) {
    setBusy(true); setMessage('Working…');
    try { const response = await fetch('/api/internal/journey-costing', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error);
      if (data.record) { setSaved(data.record); setInput(data.record.input); setRevisions(rows => [...rows, data.record]); setConfirmed(false); setMessage(`Saved revision ${data.record.version} · ${data.record.status}`); }
      if (data.preview) setMessage(`PREVIEW ONLY — proposed Journey price ${currency(data.preview.set.price)}. No Journey update executed.`);
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Operation failed'); } finally { setBusy(false); }
  }
  const latest = revisions.filter(row => row.input.journeyId === input?.journeyId && !revisions.some(other => other.id === row.id && other.version > row.version));
  const calculation = result?.calculation;
  return <main className="mx-auto max-w-7xl px-4 pb-16 pt-32 text-slate-900">
    <header className="mb-6 rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs uppercase tracking-widest text-amber-300">Internal commercial workspace · Local only</p><h1 className="mt-2 text-3xl font-semibold">Journey costing</h1><p className="mt-2 text-sm text-slate-300">Build a price from supplier quotes. Revisions stay on this computer. Production access and Journey price writes are disabled.</p></header>
    <Link href="/internal/suppliers" className="mb-4 inline-block text-sm underline">Supplier rate library and coverage</Link>
    <p role="status" aria-live="polite" className="mb-5 break-words rounded-lg bg-amber-50 p-3 text-sm text-amber-950">{message}</p>
    {input && journey && <>
      <section className="mb-5 grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-2">
        <Field label="Journey"><select className={inputClass} value={journey.journeyId} onChange={event => { const selected = journeys.find(row => row.journeyId === event.target.value)!; setInput(emptyCosting(selected)); setSaved(null); setConfirmed(false); setMessage('New scenario. Costs are blank.'); }}>{journeys.map(row => <option key={row.journeyId} value={row.journeyId}>{row.title} · {row.status}</option>)}</select></Field>
        <Field label="Load saved scenario"><select className={inputClass} value={saved?.id ?? ''} onChange={event => { const selected = latest.find(row => row.id === event.target.value); if (selected) { setSaved(selected); setInput(selected.input); setConfirmed(false); } }}><option value="">Select a local scenario</option>{latest.map(row => <option key={row.id} value={row.id}>{row.input.scenarioName} · v{row.version} · {row.status}</option>)}</select></Field>
        <div className="min-w-0 md:col-span-2"><p className="break-words text-sm"><strong>{journey.title}</strong> · {journey.status} · {journey.duration} · {journey.startingCity || 'Unspecified'} → {journey.endingCity || 'Unspecified'}</p><p className="break-all text-xs text-slate-500">{journey.journeySlug} · Current public price: {journey.price === null ? 'Not set' : currency(journey.price)}</p><details className="mt-3"><summary className="cursor-pointer text-sm font-medium">Read-only day-wise itinerary</summary><ol className="mt-3 space-y-3 text-sm">{journey.itinerary.map(day => <li key={day.day}><strong>Day {day.day}: {day.title}</strong><p>{day.description}</p></li>)}</ol></details></div>
      </section>
      <div className="grid min-w-0 items-start gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
        <div className="min-w-0 space-y-5">
          <SupplierRatePicker key={input.journeyId} input={input} add={(category, line) => update({ [category]: [...input[category], line] })} />
          <SupplierQuoteHelper key={input.journeyId + '-quote'} journey={journey} input={input} />
          <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-lg font-semibold">Traveller scenario</h2><div className="mb-4 flex flex-wrap gap-2">{[2, 4, 6].map(adults => <button key={adults} className={buttonClass} onClick={() => update({ adultCount: adults, childCount: 0, travellerCount: adults, roomCount: adults / 2 })}>{adults} adults / {adults / 2} room{adults > 2 ? 's' : ''}</button>)}</div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            <Field label="Scenario name"><input className={inputClass} value={input.scenarioName} onChange={event => update({ scenarioName: event.target.value })} /></Field>
            <Numeric label="Adults" value={input.adultCount} onChange={value => update({ adultCount: value ?? 0, travellerCount: (value ?? 0) + input.childCount })} />
            <Numeric label="Children" value={input.childCount} onChange={value => update({ childCount: value ?? 0, travellerCount: (value ?? 0) + input.adultCount })} />
            <Numeric label="Rooms" value={input.roomCount} onChange={value => update({ roomCount: value ?? 0 })} />
            <Field label="Season"><input className={inputClass} value={input.travelSeason} onChange={event => update({ travelSeason: event.target.value })} /></Field>
            <Field label="Valid from"><input type="date" className={inputClass} value={input.validFrom} onChange={event => update({ validFrom: event.target.value })} /></Field>
            <Field label="Valid to"><input type="date" className={inputClass} value={input.validTo} onChange={event => update({ validTo: event.target.value })} /></Field>
          </div><p className="mt-3 text-xs text-slate-500">Per-person costs multiply by adults + children. Enter child discounts or extra-bed costs as separately quantified lines; no child rate is assumed.</p></section>
          {COST_CATEGORIES.map(category => <section key={category} className="min-w-0 rounded-xl border bg-white p-5"><div className="mb-4 flex items-center justify-between gap-2"><h2 className="text-lg font-semibold">{labels[category]}</h2><button className={buttonClass} onClick={() => update({ [category]: [...input[category], emptyLine(crypto.randomUUID(), category)] })}>Add {labels[category].toLowerCase()}</button></div>
            {!input[category].length && <p className="text-sm text-slate-500">No supplier costs entered.</p>}
            <div className="space-y-4">{input[category].map((line, index) => <fieldset key={line.id} className="min-w-0 rounded-lg border border-slate-200 bg-slate-50 p-3"><legend className="px-1 text-xs font-semibold">{labels[category]} line {index + 1}</legend>{line.supplierRateSnapshot && <div className="mb-3 break-words text-xs"><p>Supplier rate snapshot · {line.supplierRateSnapshot.supplierRateId} · v{line.supplierRateSnapshot.supplierRateRevision} · {line.supplierRateSnapshot.snapshotRate.seasonLabel} · {line.supplierRateSnapshot.snapshotRate.validFrom}–{line.supplierRateSnapshot.snapshotRate.validTo}</p><button type="button" className={`${buttonClass} mt-2`} onClick={() => updateLine(category, line.id, { supplierRateSnapshot: null, confirmationStatus: 'ESTIMATE', notes: line.notes + '\nConverted to manual from supplier snapshot; reconfirm supplier quote.' })}>Convert snapshot to manual rate</button></div>}<fieldset disabled={!!line.supplierRateSnapshot} className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2">
              <Field label="Label"><input className={inputClass} value={line.label} onChange={event => updateLine(category, line.id, { label: event.target.value })} /></Field>
              <Field label="Supplier (optional)"><input className={inputClass} value={line.supplierName} onChange={event => updateLine(category, line.id, { supplierName: event.target.value })} /></Field>
              <Field label="Location"><input className={inputClass} value={line.location} onChange={event => updateLine(category, line.id, { location: event.target.value })} /></Field>
              {category === 'mealCosts' && <Field label="Meal type (match hotel included-meal label)"><input className={inputClass} value={line.mealType ?? ''} placeholder="breakfast, lunch, dinner, packed meal…" onChange={event => updateLine(category, line.id, { mealType: event.target.value })} /></Field>}
              <Field label="Cost basis"><select className={inputClass} value={line.costBasis} onChange={event => updateLine(category, line.id, { costBasis: event.target.value as CostLine['costBasis'], ...(event.target.value === 'INCLUDED_IN_HOTEL' ? { unitCost: 0, supplements: [] } : {}) })}>{COST_BASES.filter(basis => basis !== 'ROOM_NIGHT' || category === 'hotelCosts').filter(basis => basis !== 'PER_KM' || category === 'transportCosts').filter(basis => basis !== 'INCLUDED_IN_HOTEL' || category === 'mealCosts').map(basis => <option key={basis}>{basis}</option>)}</select></Field>
              <Numeric label={line.costBasis === 'ROOM_NIGHT' ? 'Nights' : line.costBasis === 'PER_KM' ? 'Base km' : line.costBasis === 'PER_DAY' ? 'Days' : 'Quantity / meal occurrences'} value={line.quantity} onChange={value => updateLine(category, line.id, { quantity: value ?? 0 })} />
              <Numeric label="Unit cost (INR)" nullable value={line.unitCost} onChange={value => updateLine(category, line.id, { unitCost: value })} />
              {category === 'transportCosts' && <><Field label="Vehicle"><input className={inputClass} list="costing-vehicles" value={line.vehicle} onChange={event => updateLine(category, line.id, { vehicle: event.target.value })} /><datalist id="costing-vehicles"><option>Sedan</option><option>SUV</option><option>Tempo Traveller</option></datalist></Field>{line.costBasis === 'PER_KM' && <Numeric label="Dead km" value={line.deadKm} onChange={value => updateLine(category, line.id, { deadKm: value ?? 0 })} />}</>}
              {line.costBasis === 'INCLUDED_IN_HOTEL' && <Field label="Included hotel"><select className={inputClass} value={line.includedHotelId} onChange={event => updateLine(category, line.id, { includedHotelId: event.target.value })}><option value="">Select hotel line</option>{input.hotelCosts.map(hotel => <option key={hotel.id} value={hotel.id}>{hotel.label || hotel.id}</option>)}</select></Field>}
              <Field label="Supplier confirmation"><select className={inputClass} value={line.confirmationStatus} onChange={event => updateLine(category, line.id, { confirmationStatus: event.target.value as CostLine['confirmationStatus'] })}>{CONFIRMATIONS.map(status => <option key={status}>{status}</option>)}</select></Field>
              <Field label="Quote expires"><input type="date" className={inputClass} value={line.quoteExpires} onChange={event => updateLine(category, line.id, { quoteExpires: event.target.value })} /></Field>
              <Field label="Service date"><input type="date" className={inputClass} value={line.date} onChange={event => updateLine(category, line.id, { date: event.target.value })} /></Field>
              <Field label="Notes"><textarea className={inputClass} value={line.notes} onChange={event => updateLine(category, line.id, { notes: event.target.value })} /></Field>
            </fieldset><div className="my-3 flex flex-wrap gap-4 text-xs">{(['includedInPackage', 'optional', 'taxIncluded'] as const).map(key => <label key={key} className="flex items-center gap-2"><input type="checkbox" disabled={!!line.supplierRateSnapshot && key === 'taxIncluded'} checked={line[key]} onChange={event => updateLine(category, line.id, { [key]: event.target.checked })} />{key === 'includedInPackage' ? 'Count in base package' : key === 'optional' ? 'Optional' : 'Supplier tax included'}</label>)}</div>
            <p className="mb-2 text-xs text-slate-500">Supplements are explicit quantity × rate totals: meals, extra bed/child, seasonal/mandatory charges, driver allowance, tolls, parking, state tax, permits, local/snow vehicles or other costs. They do not inherit traveller/room multipliers.</p>
            <fieldset disabled={!!line.supplierRateSnapshot}>{line.supplements.map((supplement, n) => <div key={n} className="mb-2 grid gap-2 sm:grid-cols-3"><Field label="Supplement label"><input className={inputClass} value={supplement.label} onChange={event => updateLine(category, line.id, { supplements: line.supplements.map((s, i) => i === n ? { ...s, label: event.target.value } : s) })} /></Field><Numeric label="Supplement quantity" value={supplement.quantity} onChange={value => updateLine(category, line.id, { supplements: line.supplements.map((s, i) => i === n ? { ...s, quantity: value ?? 0 } : s) })} /><Numeric label="Supplement unit cost" nullable value={supplement.unitCost} onChange={value => updateLine(category, line.id, { supplements: line.supplements.map((s, i) => i === n ? { ...s, unitCost: value } : s) })} /><button className={buttonClass} onClick={() => updateLine(category, line.id, { supplements: line.supplements.filter((_, i) => i !== n) })}>Remove supplement</button></div>)}</fieldset>
            <div className="flex flex-wrap gap-2"><button disabled={!!line.supplierRateSnapshot || line.costBasis === 'INCLUDED_IN_HOTEL'} className={buttonClass} onClick={() => updateLine(category, line.id, { supplements: [...line.supplements, { label: '', quantity: 1, unitCost: null }] })}>Add supplement</button><button className={buttonClass} onClick={() => update({ [category]: input[category].filter(item => item.id !== line.id) })}>Remove line</button><span className="self-center text-sm font-semibold">{currency(calculation?.lines.find(item => item.id === line.id)?.totalCost ?? 0)}</span></div>
            </fieldset>)}</div></section>)}
          <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-lg font-semibold">Commercial calculation</h2><div className="grid gap-3 sm:grid-cols-2">
            {(['contingency', 'commission'] as const).map(key => <div key={key} className="space-y-2"><Field label={key === 'contingency' ? 'Contingency basis' : 'Commission basis'}><select className={inputClass} value={input[key].mode} onChange={event => update({ [key]: { ...input[key], mode: event.target.value } })}><option>FIXED</option><option>PERCENT</option></select></Field><Numeric label={`${key} value`} value={input[key].value} onChange={value => update({ [key]: { ...input[key], value: value ?? 0 } })} /></div>)}
            <Field label="Pricing mode"><select className={inputClass} value={input.pricing.mode} onChange={event => update({ pricing: { ...input.pricing, mode: event.target.value as CostingInput['pricing']['mode'] } })}><option>MARKUP_ON_COST</option><option>TARGET_GROSS_MARGIN</option></select></Field>
            <Numeric label="Markup / target margin %" value={input.pricing.percent} onChange={value => update({ pricing: { ...input.pricing, percent: value ?? 0 } })} />
            <Field label="Rounding"><select className={inputClass} value={input.rounding} onChange={event => update({ rounding: event.target.value as CostingInput['rounding'] })}>{['NONE', 'NEAREST_100', 'UP_TO_499', 'UP_TO_999'].map(value => <option key={value}>{value}</option>)}</select></Field>
            <Field label="Tax label"><input className={inputClass} value={input.tax.taxLabel} onChange={event => update({ tax: { ...input.tax, taxLabel: event.target.value } })} /></Field>
            <Numeric label="Tax rate %" value={input.tax.taxRate} onChange={value => update({ tax: { ...input.tax, taxRate: value ?? 0 } })} />
            <div className="space-y-2 text-sm"><label className="flex gap-2"><input type="checkbox" checked={input.tax.taxEnabled} onChange={event => update({ tax: { ...input.tax, taxEnabled: event.target.checked } })} />Enable tax</label><label className="flex gap-2"><input type="checkbox" checked={input.tax.taxInclusive} onChange={event => update({ tax: { ...input.tax, taxInclusive: event.target.checked } })} />Calculated quote includes tax</label></div>
          </div><p className="mt-3 text-xs text-slate-500">Commission is deducted from pre-tax proceeds. Inclusive tax reduces proceeds and can lower the requested margin. Tax treatment must follow the business’s registration and accounting advice. No tax rate is assumed.</p><Field label="Internal notes — no credentials"><textarea className={inputClass} value={input.notes} onChange={event => update({ notes: event.target.value })} /></Field></section>
          <section className="rounded-xl border bg-white p-5"><h2 className="mb-3 text-lg font-semibold">Save and owner review</h2><p className="mb-3 text-sm">{saved ? `Revision ${saved.version} · ${saved.status}${dirty ? ' · Unsaved edits' : ''}` : 'Unsaved scenario'} — every save creates an immutable revision; edits reset approval.</p><div className="flex flex-wrap gap-2"><button disabled={busy || !!result?.error} className={buttonClass} onClick={() => action({ action: 'save', input, previous: saved ? { id: saved.id, version: saved.version } : null })}>Save draft revision</button><button disabled={busy || !!result?.error} className={buttonClass} onClick={() => action({ action: 'save', input, previous: null })}>Save as new scenario</button></div>
            <div className="my-3 flex flex-wrap gap-2">{(['AWAITING_SUPPLIER_CONFIRMATION', 'READY_FOR_OWNER_REVIEW'] as const).map(status => <button key={status} className={buttonClass} disabled={busy || !saved || dirty} onClick={() => action({ action: 'review', id: saved!.id, version: saved!.version, status, reviewer: '', confirm: false })}>{status === 'READY_FOR_OWNER_REVIEW' ? 'Request owner review' : 'Await supplier confirmation'}</button>)}</div>
            <Field label="Owner reviewer (local audit note, not authentication)"><input className={inputClass} value={reviewer} onChange={event => setReviewer(event.target.value)} /></Field><label className="my-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I approve this exact saved commercial basis for later preparation. This does not publish a Journey.</label>
            <button className={buttonClass} disabled={busy || dirty || saved?.status !== 'READY_FOR_OWNER_REVIEW' || !confirmed || !reviewer.trim()} onClick={() => action({ action: 'review', id: saved!.id, version: saved!.version, status: 'OWNER_APPROVED', reviewer, confirm: confirmed })}>Record owner approval</button>
            <div className="mt-4 border-t pt-4"><Field label={`Type APPLY ${journey.journeySlug} to preview`}><input className={inputClass} value={applyText} onChange={event => setApplyText(event.target.value)} /></Field><button className={`${buttonClass} mt-2`} disabled={busy || dirty || saved?.status !== 'OWNER_APPROVED' || journey.status !== 'draft'} onClick={() => action({ action: 'apply', id: saved!.id, version: saved!.version, confirmation: applyText })}>Apply approved commercial price — preview only</button><p className="mt-2 text-xs text-slate-500">No Journey price, status, slug, duration or itinerary will be written.</p></div>
            <details className="mt-4"><summary className="text-sm">Revision history</summary><ul className="mt-2 text-xs">{revisions.filter(row => row.id === saved?.id).sort((a, b) => b.version - a.version).map(row => <li key={`${row.id}-${row.version}`}>v{row.version} · {row.status} · {row.updatedAt}</li>)}</ul></details>
          </section>
        </div>
        <aside className="min-w-0 rounded-xl border bg-slate-950 p-5 text-white lg:sticky lg:top-28"><h2 className="mb-4 text-lg font-semibold">Live cost summary</h2>{result?.error && <p role="alert" className="break-words text-red-300">{result.error}</p>}{calculation && <>
          <dl className="space-y-2 text-sm">{COST_CATEGORIES.map(category => <div key={category} className="flex justify-between gap-3"><dt>{labels[category]}</dt><dd>{currency(calculation.categories[category])}</dd></div>)}{([
            ['Base supplier cost', calculation.subtotal], ['Contingency', calculation.contingency], ['Cost after contingency', calculation.costAfterContingency], ['Commission effect', calculation.commission], ['Total internal cost', calculation.totalCost], ['Selling before tax treatment', calculation.requiredSellingBeforeTax], ['Tax', calculation.taxes], ['Final selling total', calculation.sellingTotal], ['Per person', calculation.perPersonSellingPrice], ['Gross profit', calculation.grossProfit]
          ] as [string, number][]).map(([label, amount]) => <div key={label} className="flex justify-between gap-3 border-t border-slate-700 pt-2"><dt>{label}</dt><dd>{currency(amount)}</dd></div>)}</dl>
          <p className="mt-3 text-xs text-slate-300">Gross margin {calculation.grossMarginPercent}% · Markup {calculation.markupPercent}%</p><div className="my-4 rounded-lg bg-amber-300 p-3 text-slate-950"><p className="text-xs font-semibold">Recommended starting price / traveller</p><p className="text-2xl font-bold">{currency(calculation.recommendedStartingPrice)}</p><p className="text-xs">Rounded total {currency(calculation.recommendedSellingTotal)} · profit {currency(calculation.recommendedGrossProfit)}</p></div>
          <p className="text-xs">{calculation.confirmations.CONFIRMED} confirmed · {calculation.confirmations.QUOTED} quoted · {calculation.confirmations.ESTIMATE} estimated</p><p className="mt-1 text-xs">Overall: {calculation.supplierConfirmationStatus}</p>
          <ul className="mt-3 space-y-2 break-words text-xs text-amber-200">{[...calculation.warnings, ...calculation.reviewBlockers].map((warning, index) => <li key={index}>{warning}</li>)}</ul><p className="mt-3 text-xs text-slate-400">Partial totals use zero for blank lines and cannot clear owner review. This is not a customer quote.</p>
        </>}</aside>
      </div>
    </>}
  </main>;
}
