import type { HotelPackage } from '@/types/hotel';

export const hotels: HotelPackage[] = [
  {
    slug: 'spiti-valley-boutique-hotel',
    title: 'Spiti Valley Boutique Hotel',
    location: 'Kaza, Spiti Valley',
    pricePerNight: 6500,
    rating: 4.8,
    reviewCount: 112,
    category: 'Hotel',
    description: 'A modern boutique property with panoramic valley views, heated rooms, and locally sourced dining.',
    images: ['/images/hotels/spiti-valley-boutique-hotel.jpg'],
    amenities: ['Heated Rooms', 'Mountain View', 'Free Wi-Fi', 'In-house Dining'],
    featured: true
  },
  {
    slug: 'manali-riverside-resort',
    title: 'Manali Riverside Resort',
    location: 'Old Manali',
    pricePerNight: 8200,
    rating: 4.7,
    reviewCount: 189,
    category: 'Resort',
    description: 'A full-service riverside resort just minutes from Old Manali market, with a bonfire deck overlooking the Beas.',
    images: ['/images/hotels/manali-riverside-resort.jpg'],
    amenities: ['River View', 'Bonfire Deck', 'Free Parking', 'Breakfast Included'],
    featured: true
  },
  {
    slug: 'dharamshala-pine-homestay',
    title: 'Dharamshala Pine Homestay',
    location: 'McLeod Ganj, Dharamshala',
    pricePerNight: 3200,
    rating: 4.9,
    reviewCount: 76,
    category: 'Homestay',
    description: 'A family-run homestay tucked in a pine forest, offering home-cooked Himachali meals and trekking guidance.',
    images: ['/images/hotels/dharamshala-pine-homestay.jpg'],
    amenities: ['Home-cooked Meals', 'Trekking Guide', 'Free Wi-Fi'],
    featured: true
  },
  {
    slug: 'kasol-riverside-homestay',
    title: 'Kasol Riverside Homestay',
    location: 'Kasol, Parvati Valley',
    pricePerNight: 2200,
    rating: 4.6,
    reviewCount: 94,
    category: 'Homestay',
    description: 'Cosy riverside rooms run by a local family, a favorite among backpackers exploring the Parvati Valley trail.',
    images: ['/images/hotels/kasol-riverside-homestay.jpg'],
    amenities: ['River View', 'Cafe on Site', 'Bonfire Nights']
  },
  {
    slug: 'shimla-heritage-hotel',
    title: 'Shimla Heritage Hotel',
    location: 'Mall Road, Shimla',
    pricePerNight: 5400,
    rating: 4.5,
    reviewCount: 143,
    category: 'Hotel',
    description: 'A colonial-era property steps from Mall Road, blending heritage architecture with modern comfort.',
    images: ['/images/hotels/shimla-heritage-hotel.jpg'],
    amenities: ['Heritage Architecture', 'Central Location', 'Room Service']
  },
  {
    slug: 'kasol-private-villa',
    title: 'Kasol Private Villa',
    location: 'Kasol, Parvati Valley',
    pricePerNight: 9800,
    rating: 4.8,
    reviewCount: 41,
    category: 'Villa',
    description: 'A private riverside villa with its own courtyard and kitchen, ideal for families and long stays.',
    images: ['/images/hotels/kasol-private-villa.jpg'],
    amenities: ['Private Courtyard', 'Full Kitchen', 'River View']
  },
  {
    slug: 'shimla-hillside-cottage',
    title: 'Shimla Hillside Cottage',
    location: 'Kufri, near Shimla',
    pricePerNight: 7200,
    rating: 4.6,
    reviewCount: 58,
    category: 'Villa',
    description: 'A wood-panelled cottage tucked into a pine hillside, with a private fireplace and valley views.',
    images: ['/images/hotels/shimla-hillside-cottage.jpg'],
    amenities: ['Private Fireplace', 'Valley View', 'Free Parking']
  },
  {
    slug: 'spiti-high-altitude-camp',
    title: 'Spiti High-Altitude Camp',
    location: 'Kibber, Spiti Valley',
    pricePerNight: 2800,
    rating: 4.7,
    reviewCount: 67,
    category: 'Camp',
    description: 'Insulated tents pitched beneath the stars, with bonfire dinners and views of snow leopard country.',
    images: ['/images/hotels/spiti-high-altitude-camp.jpg'],
    amenities: ['Bonfire Dinners', 'Stargazing', 'Insulated Tents'],
    featured: true
  },
  {
    slug: 'kasol-riverside-camp',
    title: 'Kasol Riverside Camp',
    location: 'Kasol, Parvati Valley',
    pricePerNight: 1800,
    rating: 4.5,
    reviewCount: 88,
    category: 'Camp',
    description: 'Riverside tents with bonfire nights, a stone’s throw from the Kasol backpacker trail.',
    images: ['/images/hotels/kasol-riverside-camp.jpg'],
    amenities: ['River View', 'Bonfire Nights', 'Shared Cafe']
  },
  {
    slug: 'tirthan-valley-treehouse',
    title: 'Tirthan Valley Treehouse',
    location: 'Tirthan Valley',
    pricePerNight: 4500,
    rating: 4.9,
    reviewCount: 37,
    category: 'Treehouse',
    description: 'A raised wooden hideout among deodar pines, with the Tirthan river rushing below.',
    images: ['/images/hotels/tirthan-valley-treehouse.jpg'],
    amenities: ['River View', 'Forest Setting', 'Bonfire Nights'],
    featured: true
  },
  {
    slug: 'kullu-apple-orchard-farmstay',
    title: 'Kullu Apple Orchard Farmstay',
    location: 'Kullu Valley',
    pricePerNight: 3600,
    rating: 4.8,
    reviewCount: 52,
    category: 'Farmstay',
    description: 'Stay inside a working apple orchard, with harvest walks and home-style Himachali meals.',
    images: ['/images/hotels/kullu-apple-orchard-farmstay.jpg'],
    amenities: ['Orchard Walks', 'Home-cooked Meals', 'Farm Activities']
  },
  {
    slug: 'old-manali-backpacker-hostel',
    title: 'Old Manali Backpacker Hostel',
    location: 'Old Manali',
    pricePerNight: 900,
    rating: 4.4,
    reviewCount: 216,
    category: 'Hostel',
    description: 'Budget dorms and private rooms steps from the Old Manali cafe strip, with a rooftop common area.',
    images: ['/images/hotels/old-manali-backpacker-hostel.jpg'],
    amenities: ['Rooftop Cafe', 'Free Wi-Fi', 'Shared Kitchen'],
    featured: true
  },
  {
    slug: 'narkanda-heritage-manor',
    title: 'Narkanda Heritage Manor',
    location: 'Narkanda',
    pricePerNight: 6800,
    rating: 4.6,
    reviewCount: 44,
    category: 'Heritage',
    description: 'A restored colonial-era manor with original woodwork, orchard views, and a private library.',
    images: ['/images/hotels/narkanda-heritage-manor.jpg'],
    amenities: ['Heritage Architecture', 'Private Library', 'Orchard View']
  },
  {
    slug: 'dharamshala-guest-house-lodge',
    title: 'Dharamshala Guest House & Lodge',
    location: 'Bhagsu, Dharamshala',
    pricePerNight: 1600,
    rating: 4.5,
    reviewCount: 71,
    category: 'GuestHouse',
    description: 'A simple, welcoming lodge run by a local host, minutes from the Bhagsu waterfall trail.',
    images: ['/images/hotels/dharamshala-guest-house-lodge.jpg'],
    amenities: ['Local Host', 'Free Wi-Fi', 'Trail Access']
  }
];
