import { TourPackage } from '@/types/tour';

export const tours: TourPackage[] = [
  {
      slug: 'spiti-circuit',
      title: 'Spiti Circuit',
      category: 'Adventure',
      badge: 'Best Seller',
      location: 'Spiti Valley',
      price: '₹28,500',
      duration: '10 Days / 9 Nights',
      rating: 4.9,
      reviewCount: 140,
      highlights: ['Transport', 'Stays', 'All Meals', 'Expert Guide'],
      description: 'The ultimate high-altitude expedition through remote wilderness and alpine villages.',
      image: '/images/spiti-circuit.jpg',
      destinationSlug: 'spiti-valley',
      featured: true,
      id: ''
  },
  {
      slug: 'manali-leh-highway',
      title: 'Manali-Leh Highway',
      category: 'Adventure',
      badge: 'Adventure',
      location: 'Manali → Leh',
      price: '₹32,000',
      duration: '8 Days / 7 Nights',
      rating: 4.8,
      reviewCount: 96,
      description: "A legendary road adventure across India's most iconic mountain highway.",
      image: '/images/manali-leh-highway.jpg',
      destinationSlug: 'manali',
      id: ''
  },
  {
      slug: 'dharamshala-retreat',
      title: 'Dharamshala Retreat',
      category: 'Wellness',
      badge: 'Wellness',
      location: 'Dharamshala',
      price: '₹22,000',
      duration: '6 Days / 5 Nights',
      rating: 4.7,
      reviewCount: 78,
      description: 'Wellness, culture, and mountain trekking in the shadow of the Dhauladhar range.',
      image: '/images/dharamshala-retreat.jpg',
      destinationSlug: 'dharamshala',
      id: ''
  },
  {
      slug: 'shimla-heritage-walk',
      title: 'Shimla Heritage Walk',
      category: 'Cultural',
      badge: 'Cultural',
      location: 'Shimla',
      price: '₹14,500',
      duration: '4 Days / 3 Nights',
      rating: 4.6,
      reviewCount: 52,
      description: 'Colonial architecture, Mall Road markets, and pine-clad ridge walks.',
      image: '/images/shimla-heritage-walk.jpg',
      destinationSlug: 'shimla',
      id: ''
  },
  {
      slug: 'kasol-backpacking-trail',
      title: 'Kasol Backpacking Trail',
      category: 'Adventure',
      badge: 'Budget Friendly',
      location: 'Kasol',
      price: '₹11,000',
      duration: '5 Days / 4 Nights',
      rating: 4.5,
      reviewCount: 64,
      description: 'Riverside cafes, Parvati Valley treks, and a laid-back backpacker trail.',
      image: '/images/destination-kasol.jpg',
      destinationSlug: 'kasol',
      id: ''
  },
  {
      slug: 'villas-and-cottages',
      title: 'Villas & Cottages Retreat',
      category: 'Relaxation',
      badge: 'Cozy Stay',
      location: 'Himachal Hills',
      price: '₹18,000',
      duration: '5 Days / 4 Nights',
      rating: 4.7,
      reviewCount: 72,
      highlights: ['Villas', 'Cottages', 'Local Cuisine', 'Scenic Views'],
      description: 'A tranquil getaway with private villas and cottages nestled in serene hill landscapes.',
      image: '/images/Villas-and-Cottages.jpg',
      destinationSlug: 'himachal-hills',
      id: ''
  },
  {
      slug: 'kinnaur-rampur-trek',
      title: 'Kinnaur-Rampur Highland Trek',
      category: 'Adventure',
      badge: 'Hidden Gem',
      location: 'Kinnaur Valley',
      price: '₹26,000',
      duration: '9 Days / 8 Nights',
      rating: 4.8,
      reviewCount: 82,
      highlights: ['Transport', 'Stays', 'Meals', 'Professional Guide'],
      description: 'Explore pristine valleys with ancient apple orchards and panoramic Himalayan vistas.',
      image: '/images/kinnaur-rampur-trek.jpg',
      destinationSlug: 'kinnaur-valley',
      id: ''
  },
  {
      slug: 'tirthan-valley-escape',
      title: 'Tirthan Valley Escape',
      category: 'Wellness',
      badge: 'Nature Retreat',
      location: 'Tirthan Valley',
      price: '₹19,500',
      duration: '5 Days / 4 Nights',
      rating: 4.6,
      reviewCount: 58,
      highlights: ['Riverside Camps', 'Local Guides', 'Organic Meals', 'Yoga Sessions'],
      description: 'A serene mountain valley escape with trout streams, pine forests, and wellness activities.',
      image: '/images/tirthan-valley-escape.jpg',
      destinationSlug: 'tirthan-valley',
      id: ''
  },
  {
      slug: 'chamba-dalhousie-circuit',
      title: 'Chamba-Dalhousie Circuit',
      category: 'Cultural',
      badge: 'Heritage Tour',
      location: 'Chamba → Dalhousie',
      price: '₹16,500',
      duration: '6 Days / 5 Nights',
      rating: 4.7,
      reviewCount: 69,
      highlights: ['Transport', 'Stays', 'Meals', 'Heritage Walks'],
      description: 'Discover Himalayan crafts, ancient temples, and colonial-era hill stations in one journey.',
      image: '/images/chamba-dalhousie-circuit.jpg',
      destinationSlug: 'chamba-dalhousie',
      id: ''
  },
  {
      slug: 'narkanda-ski-resort',
      title: 'Narkanda Alpine Adventure',
      category: 'Adventure',
      badge: 'Seasonal',
      location: 'Narkanda',
      price: '₹24,000',
      duration: '4 Days / 3 Nights',
      rating: 4.5,
      reviewCount: 41,
      highlights: ['Transport', 'Stays', 'Meals', 'Equipment Included'],
      description: `Snow sports, mountain biking, and alpine meadow treks in Himachal's adventure capital.`,
      image: '/images/narkanda-alpine-adventure.jpg',
      destinationSlug: 'narkanda',
      id: ''
  }
];
