'use client';
import { RATE_TYPES, SUPPLIER_TYPES, SUPPLIER_STATUSES } from '@/models/SupplierLibrary';
export const internalInput = 'mt-1 w-full min-w-0 rounded-lg border border-slate-300 bg-white p-2 text-sm text-slate-900';
export const internalButton = 'rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 disabled:opacity-40';
const choices: Record<string, readonly string[]> = { dataClassification: ['REAL', 'DEMO_SYNTHETIC'], supplierType: SUPPLIER_TYPES, status: SUPPLIER_STATUSES, category: RATE_TYPES, currency: ['INR'], confirmationStatus: ['ESTIMATE', 'QUOTED', 'CONFIRMED'], pricingBasis: ['PER_KM', 'PER_DAY', 'FIXED_ROUTE', 'SUPPLIER_QUOTE'], deadKmPolicy: ['NOT_INCLUDED', 'SAME_RATE', 'SEPARATE_RATE', 'INCLUDED'], costBasis: ['PER_PERSON', 'PER_GROUP', 'PER_ROOM', 'PER_DAY', 'FIXED'], occupancy: ['single', 'double', 'triple'] };
export const fieldLabel = (key: string) => key.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase());
export function LibraryFields({ value, onChange, omit = [] }: { value: Record<string, unknown>; onChange: (patch: Record<string, unknown>) => void; omit?: string[] }) {
  return <div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2">{Object.entries(value).filter(([key, v]) => !omit.includes(key) && key !== 'includedByDefault' && !(v !== null && typeof v === 'object' && !Array.isArray(v))).map(([key, v]) => {
    const label = fieldLabel(key); const options = choices[key]; const date = /^(validFrom|validTo|travelFrom|travelTo)$/.test(key);
    return <label className="block min-w-0 text-xs text-slate-600" key={key}>{label}{typeof v === 'boolean' ? <input aria-label={label} className="ml-2" type="checkbox" checked={v} onChange={e => onChange({ [key]: e.target.checked })} /> : options ? <select aria-label={label} className={internalInput} value={String(v)} onChange={e => onChange({ [key]: e.target.value })}>{options.map(o => <option key={o}>{o}</option>)}</select> : key.toLowerCase().includes('notes') ? <textarea aria-label={label} className={internalInput} value={String(v)} onChange={e => onChange({ [key]: e.target.value })} /> : <input aria-label={label} className={internalInput} type={date ? 'date' : key === 'email' ? 'email' : typeof v === 'number' || v === null ? 'number' : 'text'} min="0" step="any" value={v === null ? '' : Array.isArray(v) ? v.join(', ') : String(v)} onChange={e => onChange({ [key]: Array.isArray(v) ? (e.target.value === '' ? [] : e.target.value.split(',').map(s => s.trim())) : typeof v === 'number' || v === null ? e.target.value === '' ? (v === null ? null : 0) : Number(e.target.value) : e.target.value })} />}</label>;
  })}</div>;
}
