'use client';
import { useEffect, useState } from 'react';
import { COST_CATEGORIES, type CostLine, type CostingInput } from '@/models/JourneyCosting';
import type { Supplier, SupplierRate, RateSelection } from '@/models/SupplierLibrary';
import { emptySelection, matchingRates } from '@/services/pricing/supplierLibrary.service';
import { calculateJourneyCosting } from '@/services/pricing/journeyCosting.service';
import { internalButton as button, internalInput as inputClass, LibraryFields } from './SupplierLibraryFields';
const money = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(n);
export default function SupplierRatePicker({ input, add }: { input: CostingInput; add: (category: RateSelection['category'], line: CostLine) => void }) {
  const [library, setLibrary] = useState<{ suppliers: Supplier[]; rates: SupplierRate[] }>({ suppliers: [], rates: [] });
  const [selection, setSelection] = useState(emptySelection('hotelCosts')); const [destination, setDestination] = useState(''); const [supplierId, setSupplierId] = useState(''); const [rateId, setRateId] = useState('');
  const [preview, setPreview] = useState<{ line: CostLine; warnings: string[] } | null>(null); const [message, setMessage] = useState(''); const [include, setInclude] = useState(true); const [busy, setBusy] = useState(false);
  async function load() { try { const r = await fetch('/api/internal/supplier-library', { cache: 'no-store' }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setLibrary(data); setPreview(null); } catch (e) { setMessage((e as Error).message); } }
  useEffect(() => { let active = true; fetch('/api/internal/supplier-library', { cache: 'no-store' }).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); if (active) setLibrary(result); }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, []);
  const candidates = matchingRates(library.rates, library.suppliers, { category: selection.category, destination, supplierId, travelFrom: selection.travelFrom, travelTo: selection.travelTo });
  async function select() {
    const rate = candidates.find(r => r.id === rateId); if (!rate) { setMessage('Choose one matching supplier rate explicitly'); return; }
    setBusy(true); setPreview(null);
    try { const r = await fetch('/api/internal/supplier-library', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'selectRate', previous: { id: rate.id, version: rate.version }, selection: { ...selection, rooms: input.roomCount, travellers: input.travellerCount }, explicitSelection: true }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setPreview(data); setMessage(`Selected ${data.supplierVerification} supplier; rate status remains ${data.line.confirmationStatus}`); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
  }
  const readyLine = preview ? { ...preview.line, includedInPackage: include } : null;
  let impact = ''; let error = '';
  if (readyLine) try { const result = calculateJourneyCosting({ ...input, [selection.category]: [...input[selection.category], readyLine] }); impact = `New supplier base: ${money(result.subtotal)} · package selling: ${money(result.sellingTotal)} · per person: ${money(result.perPersonSellingPrice)}`; } catch (e) { error = (e as Error).message; }
  return <section className="min-w-0 rounded-xl border bg-white p-5"><h2 className="mb-3 text-lg font-semibold">Add from Supplier Rate</h2><p className="mb-3 text-xs text-slate-500">Manual rate entry remains available below. Exact suggestions only; no supplier is selected automatically. Pick service dates and quantities explicitly.</p>
    <div className="grid min-w-0 gap-3 sm:grid-cols-2"><label className="text-xs">Cost category<select aria-label="Supplier cost category" className={inputClass} value={selection.category} onChange={e => { const category = e.target.value as RateSelection['category']; setSelection(s => ({ ...s, category })); setRateId(''); setPreview(null); setInclude(!['activityCosts', 'localServiceCosts'].includes(category)); }}>{COST_CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></label>
      <label className="text-xs">Destination<select aria-label="Supplier destination" className={inputClass} value={destination} onChange={e => { setDestination(e.target.value); setRateId(''); setPreview(null); }}><option value="">All destinations (choose explicitly)</option>{[...new Set(library.rates.map(r => r.input.destination))].map(d => <option key={d}>{d}</option>)}</select></label>
      <label className="text-xs">Supplier<select aria-label="Supplier choice" className={inputClass} value={supplierId} onChange={e => { setSupplierId(e.target.value); setRateId(''); setPreview(null); }}><option value="">All active suppliers</option>{library.suppliers.filter(s => s.input.status === 'ACTIVE').map(s => <option key={s.id} value={s.id}>{s.input.name}</option>)}</select></label>
      <label className="text-xs">Rate<select aria-label="Supplier rate choice" className={inputClass} value={rateId} onChange={e => { setRateId(e.target.value); setPreview(null); }}><option value="">Select exact rate</option>{candidates.map(r => <option key={r.id} value={r.id}>{library.suppliers.find(s => s.id === r.input.supplierId)?.input.name} · {r.input.hotel?.propertyName || r.input.transport?.vehicleType || r.input.service?.activityName} · {r.input.seasonLabel} · {r.input.validFrom}–{r.input.validTo} · {r.input.confirmationStatus} · v{r.version}</option>)}</select></label>
    </div>
    <div className="mt-3"><LibraryFields value={selection as unknown as Record<string, unknown>} omit={['category', 'rooms', 'travellers']} onChange={patch => { setSelection(s => ({ ...s, ...patch })); setPreview(null); }} /></div>
    <label className="my-3 flex gap-2 text-xs"><input aria-label="Include selected supplier rate in base" type="checkbox" checked={include} onChange={e => setInclude(e.target.checked)} />Include selected supplier rate in base package</label>
    <p className="mb-3 text-xs">Hotel quantity = nights. Extra adults/children = total guest counts, charged per night. Weekend/peak nights must be explicitly counted. Transport quantity = km/days/one fixed quote; Days controls minimum km and driver allowances. Night allowances use their own count. Excluded charges need separate quotes.</p>
    <div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy || !rateId} onClick={select}>Preview selected supplier rate</button><button type="button" className={button} onClick={load}>Refresh supplier rates</button></div>
    <p role="status" className="mt-3 break-words text-xs">{message}</p>{preview && <div className="mt-3 rounded-lg bg-amber-50 p-3"><p className="break-words text-sm">{impact || error}</p><ul className="mt-2 break-words text-xs">{preview.warnings.map(w => <li key={w}>{w}</li>)}</ul><p className="mt-2 text-xs">Financial snapshot is immutable; later master-rate edits cannot change this line.</p><button type="button" className={`${button} mt-3`} disabled={!!error || !readyLine} onClick={() => { if (readyLine) add(selection.category, readyLine); setPreview(null); setMessage('Rate snapshot added. Save a costing draft to retain it.'); }}>Add rate snapshot to costing</button></div>}
  </section>;
}
