'use client';
import { useState, type ReactNode } from 'react';
import { X } from 'lucide-react';
import { FloatingOverlay } from '@/components/ui/FloatingOverlay';
import { Button, ButtonLink } from '@/components/ui/Button';
import { Input, Textarea } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import { Skeleton } from '@/components/ui/Skeleton';
import { LEAD_PRIORITIES, LEAD_STATUSES } from '@/lib/leads';
import type { InternalLead } from '@/services/leads/lead.service';
import { acquisitionLabel, captureLabel, dateLabel, leadName, phoneLink, publisherLabel, titleCase, travellersLabel, unavailable, whatsappLink } from './leadDisplay';
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="space-y-3 border-b border-slate-200 pb-5"><h3 className="font-semibold">{title}</h3>{children}</section>; }
function Fields({ rows }: { rows: [string, string | undefined][] }) { return <dl className="grid min-w-0 gap-3 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className="min-w-0"><dt className="text-xs text-slate-600">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm">{value || unavailable}</dd></div>)}</dl>; }
export function LeadDetailDrawer({ open, lead, loading, error, busy, onClose, onRetry, onAction }: { open: boolean; lead: InternalLead | null; loading: boolean; error: string; busy: boolean; onClose: () => void; onRetry: () => void; onAction: (body: Record<string, unknown>) => Promise<boolean> }) {
  return <FloatingOverlay open={open} onClose={onClose} label="Lead details" overlayClassName="justify-end overflow-hidden bg-slate-950/40 p-0 sm:p-0" panelClassName="my-0 flex h-[100dvh] max-w-none flex-col bg-white sm:max-w-xl"><header className="flex shrink-0 items-start justify-between gap-3 border-b border-slate-200 p-4 sm:p-6"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-apex-700">Lead details</p><h2 className="mt-1 break-words text-xl font-semibold">{lead && !loading ? leadName(lead) : 'Customer enquiry'}</h2></div><Button variant="secondary" className="min-h-11 min-w-11 px-2" aria-label="Close lead details" disabled={busy} onClick={onClose}><X size={20} /></Button></header><div className="min-h-0 flex-1 space-y-5 overflow-y-auto overscroll-contain p-4 sm:p-6" aria-busy={loading || busy}>{error ? <div role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800"><p>{error}</p><Button variant="secondary" className="mt-3" onClick={onRetry} disabled={busy}>Retry</Button></div> : null}{loading ? <div role="status" className="space-y-4"><p>Loading lead details…</p><Skeleton className="h-28 animate-none" /><Skeleton className="h-48 animate-none" /></div> : lead ? <DetailContent key={lead.id} lead={lead} busy={busy} onAction={onAction} /> : null}</div></FloatingOverlay>;
}
function DetailContent({ lead, busy, onAction }: { lead: InternalLead; busy: boolean; onAction: (body: Record<string, unknown>) => Promise<boolean> }) {
  const [note, setNote] = useState(''); const [followUp, setFollowUp] = useState(''); const phone = lead.phone || lead.whatsappNumber;
  return <><Section title="Customer information"><Fields rows={[["Name", lead.name], ['Phone', phone], ['Email', lead.email]]} /><div className="flex flex-wrap gap-2">{phone ? <><ButtonLink variant="secondary" size="sm" href={`tel:${phoneLink(phone)}`}>Call</ButtonLink><ButtonLink variant="secondary" size="sm" href={whatsappLink(phone)} target="_blank" rel="noopener noreferrer">WhatsApp</ButtonLink></> : null}<Button variant="secondary" size="sm" disabled={busy} onClick={() => void onAction({ action: 'record_contacted' })}>Record contacted</Button></div></Section>
  <Section title="Travel requirements"><Fields rows={[["Package", lead.journeySlug], ['Destination', lead.destination], ['Travel start', dateLabel(lead.travelStartDate)], ['Travel end', dateLabel(lead.travelEndDate)], ['Duration', lead.duration], ['Travellers', travellersLabel(lead)], ['Budget', lead.budget], ['Pickup', lead.pickupLocation], ['Travel style', lead.travelStyle], ['Requirements', lead.message]]} /></Section>
  <Section title="Lead attribution"><Fields rows={[["Capture channel", captureLabel(lead)], ['Acquisition source', acquisitionLabel(lead)], ['Source detail', lead.sourceDetail], ['Campaign name', lead.meta?.campaignName], ['Campaign ID', lead.meta?.campaignId], ['Ad set name', lead.meta?.adSetName], ['Ad set ID', lead.meta?.adSetId], ['Ad name', lead.meta?.adName], ['Ad ID', lead.meta?.adId], ['Form name', lead.meta?.formName], ['Form ID', lead.meta?.formId], ['Publisher platform', publisherLabel(lead)], ['Landing page', lead.landingPage], ['Referrer', lead.referrer], ['UTM source', lead.utmSource], ['UTM medium', lead.utmMedium], ['UTM campaign', lead.utmCampaign], ['UTM content', lead.utmContent], ['UTM term', lead.utmTerm], [lead.meta?.leadId.startsWith('lc:') ? 'Import reference (not a Meta ID)' : 'External lead ID', lead.meta?.leadId], ['Submitted', dateLabel(lead.meta?.createdTime, true)], ['CRM created', dateLabel(lead.createdAt, true)]]} /></Section>
  <Section title="Follow-up management"><Fields rows={[["Last contact", dateLabel(lead.lastContactedAt, true)], ['Next follow-up', dateLabel(lead.nextFollowUpAt, true)], ['Follow-up state', titleCase(lead.followUp)]]} /><div className="grid gap-3 sm:grid-cols-2"><Select id="detail-status" label="Status" value={lead.status} disabled={busy} onChange={e => void onAction({ action: 'set_status', status: e.target.value, reopen: true })}>{LEAD_STATUSES.map(s => <option key={s} value={s}>{titleCase(s)}</option>)}</Select><Select id="detail-priority" label="Priority" value={lead.priority} disabled={busy} onChange={e => void onAction({ action: 'set_priority', priority: e.target.value })}>{LEAD_PRIORITIES.map(s => <option key={s} value={s}>{titleCase(s)}</option>)}</Select></div><div className="flex flex-wrap gap-2">{(['WON', 'LOST', 'SPAM'] as const).map(status => <Button key={status} variant="secondary" size="sm" disabled={busy || lead.status === status} onClick={() => void onAction({ action: 'set_status', status })}>Mark {status.toLowerCase()}</Button>)}</div><p className="text-xs text-slate-600">Progress reflects CRM status, not verified booking confirmation.</p><form className="space-y-3" onSubmit={async e => { e.preventDefault(); if (followUp && await onAction({ action: 'schedule_follow_up', at: new Date(followUp).toISOString() })) setFollowUp(''); }}><Input id="detail-followup" label="Schedule follow-up (your local time)" type="datetime-local" required value={followUp} disabled={busy} onChange={e => setFollowUp(e.target.value)} /><div className="flex flex-wrap gap-2"><Button type="submit" size="sm" disabled={busy || !followUp}>Set follow-up</Button><Button type="button" variant="secondary" size="sm" disabled={busy || !lead.nextFollowUpAt} onClick={() => void onAction({ action: 'schedule_follow_up', at: null })}>Clear follow-up</Button></div></form></Section>
  <Section title="Internal notes"><form className="space-y-3" onSubmit={async e => { e.preventDefault(); if (note.trim() && await onAction({ action: 'add_note', text: note.trim() })) setNote(''); }}><Textarea id="detail-note" label="Add a note" rows={3} maxLength={2000} value={note} disabled={busy} onChange={e => setNote(e.target.value)} /><Button type="submit" size="sm" disabled={busy || !note.trim()}>Add note</Button></form></Section>
  <Section title="Activity history">{lead.events.length ? <ol className="space-y-4">{[...lead.events].reverse().map((event, i) => <li key={`${event.at}-${i}`} className="border-l-2 border-apex-100 pl-3 text-sm"><p className="font-medium">{titleCase(event.type)}</p><p className="mt-1 break-words text-xs text-slate-600">{dateLabel(event.at, true)} · {event.actor}</p>{event.from || event.to ? <p className="mt-1">{event.from ? titleCase(event.from) : unavailable} → {event.to ? titleCase(event.to) : unavailable}</p> : null}{event.text ? <p className="mt-1 whitespace-pre-wrap break-words text-slate-700">{event.text}</p> : null}</li>)}</ol> : <p className="text-sm text-slate-600">No recorded activity.</p>}</Section></>;
}
