'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { SUPPLIER_STATUSES, VERIFICATION_STATES, RATE_TYPES, type Supplier, type SupplierInput, type SupplierRate, type SupplierRateInput } from '@/models/SupplierLibrary';
import { emptySupplier, emptyRate, rateValidity, validateRate, validateSupplier } from '@/services/pricing/supplierLibrary.service';
import { LibraryFields, internalButton as button, internalInput as inputClass } from '@/components/internal/SupplierLibraryFields';
import type { supplierCoverage } from '@/services/pricing/supplierCoverage.service';
interface Data { suppliers: Supplier[]; rates: SupplierRate[]; supplierHistory: Supplier[]; rateHistory: SupplierRate[]; coverage: ReturnType<typeof supplierCoverage> }
const money = (n: number | null) => n === null ? 'Unquoted' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(n);
export default function SupplierLibraryClient() {
  const [data, setData] = useState<Data | null>(null); const [message, setMessage] = useState('Loading local supplier library…'); const [busy, setBusy] = useState(false);
  const [supplierInput, setSupplierInput] = useState<SupplierInput>(emptySupplier()); const [supplier, setSupplier] = useState<Supplier | null>(null);
  const [rateInput, setRateInput] = useState<SupplierRateInput>(emptyRate()); const [rate, setRate] = useState<SupplierRate | null>(null);
  const [verification, setVerification] = useState<Supplier['verificationStatus']>('CONTACTED'); const [verificationNotes, setVerificationNotes] = useState(''); const [verificationText, setVerificationText] = useState('');
  const [filter, setFilter] = useState({ supplierId: '', destination: '', category: '', status: '', validity: '' });
  async function load() { const response = await fetch('/api/internal/supplier-library', { cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); }
  useEffect(() => { let active = true; fetch('/api/internal/supplier-library', { cache: 'no-store' }).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); if (active) { setData(result); setMessage('No supplier data is sent to public APIs. Enter real quotes only.'); } }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, []);
  async function action(payload: unknown) {
    setBusy(true); try { const r = await fetch('/api/internal/supplier-library', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await r.json(); if (!r.ok) throw new Error(result.error);
      await load(); if (result.record.input.supplierType) { setSupplier(result.record); setSupplierInput(result.record.input); } else { setRate(result.record); setRateInput(result.record.input); }
      setVerificationText(''); setMessage(`Saved local revision ${result.record.version}`);
    } catch (e) { setMessage(e instanceof Error ? e.message : 'Local save failed'); } finally { setBusy(false); }
  }
  const filtered = data?.rates.filter(r => (!filter.supplierId || r.input.supplierId === filter.supplierId) && (!filter.destination || r.input.destination === filter.destination) && (!filter.category || r.input.category === filter.category) && (!filter.status || r.input.confirmationStatus === filter.status) && (!filter.validity || rateValidity(r.input) === filter.validity)) ?? [];
  let supplierError = ''; let rateError = ''; try { validateSupplier(supplierInput); } catch (e) { supplierError = (e as Error).message; } try { validateRate(rateInput); } catch (e) { rateError = (e as Error).message; }
  return <main className="mx-auto min-w-0 max-w-7xl px-4 pb-16 pt-32 text-slate-900">
    <header className="mb-5 rounded-xl bg-slate-950 p-6 text-white"><p className="text-xs text-amber-300">Internal · local only</p><h1 className="text-3xl font-semibold">Supplier and rate library</h1><p className="mt-2 text-sm">Reusable supplier contracts with immutable revisions. Production access is blocked. No Journey data is written.</p><Link href="/internal/journey-costing" className="mt-3 inline-block underline">Open Journey costing</Link></header>
    <p role="status" className="mb-5 break-words rounded-lg bg-amber-50 p-3 text-sm">{message}</p>
    <div className="grid min-w-0 gap-5 lg:grid-cols-2">
      <section className="min-w-0 rounded-xl border bg-white p-5"><h2 className="mb-3 text-xl font-semibold">Suppliers</h2><div className="mb-4 flex flex-wrap gap-2"><button className={button} onClick={() => { setSupplier(null); setSupplierInput(emptySupplier()); }}>New supplier</button>{data?.suppliers.map(s => <button key={s.id} className={`${button} max-w-full break-words text-left`} onClick={() => { setSupplier(s); setSupplierInput(s.input); }}>{s.input.name} · {s.input.status} · {s.verificationStatus}</button>)}</div>
        <LibraryFields value={supplierInput as unknown as Record<string, unknown>} onChange={patch => setSupplierInput(current => ({ ...current, ...patch }))} />
        <p className="mt-3 break-words text-xs text-amber-800">{supplierError}</p><button disabled={busy || !!supplierError} className={`${button} mt-3`} onClick={() => action({ action: 'saveSupplier', input: supplierInput, previous: supplier ? { id: supplier.id, version: supplier.version } : null })}>Save supplier</button>
        {supplier && <div className="mt-5 space-y-3 border-t pt-4"><h3 className="font-semibold">Supplier detail</h3><p className="text-sm">{supplier.input.name} · v{supplier.version} · {supplier.verificationStatus} · {supplier.verifiedAt || 'Not verified'}</p><p className="break-words text-xs">{supplier.verificationNotes}</p><button disabled={busy || supplier.input.status === 'INACTIVE'} className={button} onClick={() => action({ action: 'saveSupplier', input: { ...supplier.input, status: 'INACTIVE' }, previous: { id: supplier.id, version: supplier.version } })}>Deactivate supplier</button>
          <label className="block text-xs">Verification state<select aria-label="Verification state" className={inputClass} value={verification} onChange={e => setVerification(e.target.value as Supplier['verificationStatus'])}>{VERIFICATION_STATES.map(s => <option key={s}>{s}</option>)}</select></label>
          <label className="block text-xs">Verification notes<textarea aria-label="Verification notes" className={inputClass} value={verificationNotes} onChange={e => setVerificationNotes(e.target.value)} /></label>
          <label className="block break-all text-xs">Type VERIFY {supplier.id} for VERIFIED<input aria-label="Verification acknowledgement" className={inputClass} value={verificationText} onChange={e => setVerificationText(e.target.value)} /></label>
          <button disabled={busy} className={button} onClick={() => action({ action: 'verifySupplier', previous: { id: supplier.id, version: supplier.version }, status: verification, notes: verificationNotes, confirmation: verificationText })}>Record verification</button>
          <p className="text-xs">Active/current rates: {data?.rates.filter(r => r.input.supplierId === supplier.id && rateValidity(r.input) !== 'EXPIRED').length} · Expired: {data?.rates.filter(r => r.input.supplierId === supplier.id && rateValidity(r.input) === 'EXPIRED').length}</p><ul className="space-y-1 text-xs">{data?.rates.filter(r => r.input.supplierId === supplier.id).map(r => <li key={r.id}>{r.input.category} · {r.input.destination} · {rateValidity(r.input)} · {r.input.confirmationStatus}</li>)}</ul>
        </div>}
      </section>
      <section className="min-w-0 rounded-xl border bg-white p-5"><h2 className="mb-3 text-xl font-semibold">Rate entry</h2><button className={`${button} mb-3`} onClick={() => { setRate(null); setRateInput(emptyRate(supplier?.id ?? '')); }}>New rate</button>
        <label className="mb-3 block text-xs">Supplier<select aria-label="Rate supplier" className={inputClass} value={rateInput.supplierId} disabled={!!rate} onChange={e => setRateInput(r => ({ ...r, supplierId: e.target.value }))}><option value="">Select supplier</option>{data?.suppliers.filter(s => s.input.status !== 'INACTIVE').map(s => <option key={s.id} value={s.id}>{s.input.name}</option>)}</select></label>
        <label className="mb-3 block text-xs">Rate category<select aria-label="Rate category" className={inputClass} value={rateInput.category} disabled={!!rate} onChange={e => setRateInput(r => ({ ...emptyRate(r.supplierId, e.target.value as SupplierRateInput['category']), destination: r.destination, validFrom: r.validFrom, validTo: r.validTo, confirmationStatus: r.confirmationStatus }))}>{RATE_TYPES.map(t => <option key={t}>{t}</option>)}</select></label>
        <LibraryFields value={rateInput as unknown as Record<string, unknown>} omit={['supplierId', 'category']} onChange={patch => setRateInput(r => ({ ...r, ...patch }))} />
        {(['hotel', 'transport', 'service'] as const).map(section => rateInput[section] && <div className="mt-4 rounded-lg bg-slate-50 p-3" key={section}><h3 className="mb-3 font-semibold">{section === 'hotel' ? 'Hotel room / night' : section === 'transport' ? 'Supplier transport' : 'Service quote'}</h3><LibraryFields value={rateInput[section] as unknown as Record<string, unknown>} onChange={patch => setRateInput(r => ({ ...r, [section]: { ...r[section], ...patch } }))} /></div>)}
        <p className="mt-3 break-words text-xs text-amber-800">{rateError}</p><button disabled={busy || !!rateError} className={`${button} mt-3`} onClick={() => action({ action: 'saveRate', input: rateInput, previous: rate ? { id: rate.id, version: rate.version } : null })}>{rate ? 'Save rate revision' : 'Save new rate'}</button>
        <p className="mt-3 text-xs text-slate-500">Hotel supplements are INR per room-night; extra adult/child rates per guest-night. Driver allowance is per day. Enter no credentials. Tax inclusion describes the supplier quote, not a business GST treatment.</p>
      </section>
    </div>
    <section className="mt-5 rounded-xl border bg-white p-5"><h2 className="mb-3 text-xl font-semibold">Rate comparison and history</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(filter).map(([key, value]) => <label className="min-w-0 text-xs" key={key}>{key}<select aria-label={`Filter ${key}`} className={inputClass} value={value} onChange={e => setFilter(f => ({ ...f, [key]: e.target.value }))}><option value="">All</option>{(key === 'supplierId' ? data?.suppliers.map(s => ({ value: s.id, label: s.input.name })) ?? [] : (key === 'category' ? [...RATE_TYPES] : key === 'status' ? ['ESTIMATE', 'QUOTED', 'CONFIRMED'] : key === 'validity' ? ['ACTIVE', 'EXPIRING_SOON', 'EXPIRED', 'FUTURE'] : [...new Set(data?.rates.map(r => r.input.destination))]).map(v => ({ value: v, label: v }))).map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>)}</div>
      <p className="my-3 text-xs">Comparison is for owner selection. No cheapest supplier is chosen automatically. Rates with different basis, occupancy, meal plan or inclusions are not equivalent.</p><div className="grid min-w-0 gap-3 md:grid-cols-2">{filtered.map(r => <article className="min-w-0 rounded-lg border p-3 text-sm" key={r.id}><p className="break-words font-semibold">{data?.suppliers.find(s => s.id === r.input.supplierId)?.input.name} · {r.input.category} · {r.input.destination}</p><p>{money(r.input.hotel?.doubleOccupancyRate ?? r.input.transport?.ratePerKm ?? r.input.transport?.ratePerDay ?? r.input.transport?.fixedRouteAmount ?? r.input.service?.rate ?? null)} · {r.input.hotel ? 'double room/night' : r.input.transport?.pricingBasis || r.input.service?.costBasis}</p><p className="break-words text-xs">{r.input.seasonLabel} · {r.input.validFrom}–{r.input.validTo} · {rateValidity(r.input)} · {r.input.confirmationStatus} · v{r.version}</p><button className={`${button} mt-2`} onClick={() => { setRate(r); setRateInput(r.input); }}>Edit / create revision</button><details className="mt-2 text-xs"><summary>Rate revision history</summary>{data?.rateHistory.filter(h => h.id === r.id).sort((a, b) => b.version - a.version).map(h => <p key={h.version}>v{h.version} · {h.updatedAt} · {h.input.confirmationStatus} · {money(h.input.hotel?.doubleOccupancyRate ?? h.input.transport?.fixedRouteAmount ?? h.input.service?.rate ?? null)}</p>)}</details></article>)}</div>
    </section>
    <section className="mt-5 rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Draft supplier coverage</h2>{data && <><p className="my-3 text-sm">{data.coverage.summary.draftJourneys} drafts · Hotel route candidates {data.coverage.summary.hotel}/{data.coverage.summary.draftJourneys} · Whole-route transport {data.coverage.summary.transport}/{data.coverage.summary.draftJourneys} · Complete confirmed costing {data.coverage.summary.fullyCostable}/{data.coverage.summary.draftJourneys} · Awaiting quote/costing {data.coverage.summary.awaitingQuote} · Expired rates {data.coverage.summary.expired}</p><div className="grid min-w-0 gap-3 md:grid-cols-2">{data.coverage.rows.map(r => <article className="min-w-0 rounded-lg border p-3" key={r.slug}><h3 className="break-words font-semibold">{r.title}</h3><p className="break-words text-xs">{r.slug} · {r.duration}</p><p className="mt-2 text-sm">Hotel destinations to confirm: {r.hotelDestinations.join(', ') || 'Unknown'}</p><p className="my-2 text-xs">Overnight/base evidence: {r.overnightEvidence.map(d => `Day ${d.day}: ${d.title} — ${d.description}`).join('; ') || 'No explicit overnight plan; owner must confirm'}</p><p className="text-xs">Transport context: {r.transportLegs.map(l => `Day ${l.day}: ${l.label}`).join('; ')}</p><p className="text-xs">Possible local/optional: {r.possibleLocalServices.join(', ') || 'Owner to confirm; unpriced'}</p><ul className="my-2 break-words text-xs text-amber-800">{r.missing.map(m => <li key={m}>{m}</li>)}</ul><p className="text-xs text-slate-500">{r.caveat}</p></article>)}</div></>}</section>
    <p className="mt-5 text-xs text-slate-500">Supplier status options: {SUPPLIER_STATUSES.join(', ')}. Supplier verification and rate confirmation are separate; neither publishes a Journey.</p>
  </main>;
}
